### ISSUE TITLE
TODO: Create a stable regenerative database using JSON files rather than faker functions.

### ISSUE THREAD

**Issue by Rian501** [Funky-Chickens/Bangazon-CLI#12]
- [x] Use faker data to generate json files
- [x] Save JSON files to db folder
- [x] refactor database creation/populations functions to take in the JSON files rather than fetching faker data
